# Generated by Django 2.2.16 on 2022-03-09 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220303_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measure',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='countofingredient',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Величина не может быть меньше 1')], verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Величина не может быть меньше 1')]),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
