version: "3.7"

services:
  db:
    container_name: foodgram_postgres
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  pgadmin:
    container_name: foodgram_pgadmin
    image: dpage/pgadmin4:5.7
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "5050:80"
    restart: unless-stopped

  backend:
    container_name: foodgram_backend
    build:
      context: ../backend/api_foodgram
      dockerfile: Dockerfile
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    container_name: foodgram_frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    container_name: foodgram_nginx
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs:/usr/share/nginx/html/api/docs/
      - static_value:/var/www/static/
      - media_value:/var/www/media/

    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value:

