version: "3.7"

services:
  db:
    container_name: foodgram_postgres
    image: postgres:13.0-alpine
    volumes:
      - ../application/postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  pgadmin:
    container_name: foodgram_pgadmin
    image: dpage/pgadmin4:5.7
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "5050:80"
    restart: unless-stopped

  backend:
    container_name: foodgram_backend
    image: priest4612/foodgram:v.1.3.22.03.2022
    volumes:
      - ../application/static_value:/app/static_backend/
      - ../application/media_value:/app/media_backend/
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    container_name: foodgram_frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../application/frontend/:/app/result_build/
    depends_on:
      - backend
    env_file:
      - ./.env

  nginx:
    container_name: foodgram_nginx
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../application/frontend/build:/usr/share/nginx/html/
      - ../application/docs:/usr/share/nginx/html/api/docs/
      - ../application/static_value:/var/www/static_backend/
      - ../application/media_value:/var/www/media_backend/

    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value:

